ren "Bleu Blanc Minimaliste Simple Moderne Typographic Ciel Azur Galerie D'art Logo.png" "logo.png"
ren "Box cœur Ferrero premium.png" "box-coeur-ferrero-premium.png"
ren "choco box etage.png" "choco-box-etage.png"
ren "Box cœur rose Ferrero.png" "box-coeur-rose-ferrero.png"
ren "box coeur rouge.png" "box-coeur-rouge.png"
ren "Box cœur romantique.png" "box-coeur-romantique.png"
ren "Box cœur Ferrero rouge.png" "box-coeur-ferrero-rouge.png"
ren "Box anniversaire etaage.png" "box-anniversaire-etage.png"
ren "Box cœur love.png" "box-coeur-love.png"
ren "Box cœur violet.png" "box-coeur-violet.png"
ren "Box cœur chocolat mix.png" "box-coeur-chocolat-mix.png"
ren "box coeur marriage.png" "box-coeur-mariage.png"
ren "box ronde snickers.png" "box-ronde-snickers.png"
ren "box ronde ferroro.png" "box-ronde-ferrero.png"
ren "box coeaur ferrero.png" "box-coeur-ferrero.png"
ren "box couer red and white.png" "box-coeur-rouge-blanc.png"
ren "Mini box cœur.png" "mini-box-coeur.png"
